### PR TITLE
fix mangled project name

### PR DESCRIPTION
**Pull request by costela**
Somehow during the merging of #27 the project name got mangled. The PR looks OK, the actually merged code does not. :man_shrugging:   
Unfortunately I only noticed it now.

### CODE REVIEW

**Comment by LKaemmerling** [comment]
Fixed with 7bfc2161682143c88de06d5388761308e0d58d75, thank you!

**Comment by costela** [comment]
@LKaemmerling nope, still mangled. Compare this PR's changes with the commit you just linked: the applied commit has the `-kubernetes-controller` suffix, which was removed in this PR.

In a more general note: why not simply *merge* the PRs instead of having this weird close-PR-and-add-fake-commit workflow? From a user's perspective it feels somewhat hacky to not even attribute the change correctly (though I acknowledge there might be some reason for it I'm overlooking).

**Comment by LKaemmerling** [comment]
Fixed with 846caeb4aed63f07c85ecbf3895df4f743860463 .

@costela we use a small CMS system to publish and generate this awesome list because we need to publish the integrations (and libraries) on https://developers.hetzner.com/cloud/libraries too. 

I'm sorry that I just overlocked the change, as long as I remember was the old repository name something with "Kubernetes Controller", I just copy and paste the name in the readme of every project.

**Comment by costela** [comment]
@LKaemmerling understandable. Thanks for the quick fix!

**Pull request closed without merging**
