### PR TITLE
add hetzner app

### PR DESCRIPTION
**Pull request by jonathan-martz**

### CODE REVIEW

**Comment by jonathan-martz** [comment]
Live Version is under www.hetzner.app

**Comment by LenzGr** [comment]
Thank you for your contribution and sorry for the late reply @jonathan-martz! The live version seems to be no longer available - do you still maintain this project?

**Comment by jonathan-martz** [comment]
Currently planning to do a rewrite of my old version to a new Version with Nuxt 3 and VueJs 3.

Setup today the Code Base under:
https://gitlab.jonathan-martz.de/softwareentwicklung/hetzner-app

Live Domain:
https://www.hetzner.app

Will take a few days to add the logic for servers and so on.

I will work a few days on it and the i will submit a new pull request to add it to your list, okay ?

**Comment by LenzGr** [comment]
Sounds good, let's close this PR then. Thank you!

**Comment by jooola** [comment]
Instead of opening a pull request, please open an issue describing your project. We do not merge pull requests in this repository.

**Pull request closed without merging**
